export const solutionSlugs = ["vessel-reactivation", "planned-maintenance", "remote-site-supply"] as const;
export type SolutionSlug = typeof solutionSlugs[number];
type Solution = { title: string; intro: string; local: string[]; group: string[]; prepare: string[]; evidence: string; image: string; evidenceHref: string; groupHref: string };
const evidence = {
  "vessel-reactivation": { image: "/images/site/operations/container-lift-subsea7.jpg", evidenceHref: "/insights/reviving-sapura-berani", groupHref: "https://daron-group.com/ship-chandling/" },
  "planned-maintenance": { image: "/images/site/drydock/case-study-hempel-bow.jpg", evidenceHref: "/services/dry-dock", groupHref: "https://daron-group.com/technical/" },
  "remote-site-supply": { image: "/images/site/operations/daron-fleet-normand-energy.jpg", evidenceHref: "https://daron-group.com/ngo-project-in-mueda/", groupHref: "https://daron-group.com/dfood/" },
};
const en = {
  networkEyebrow: "NAMIBIA & THE DARON GROUP", networkTitle: "Local accountability. Group capability.",
  networkIntro: "Start with our Walvis Bay team. For requirements involving other markets or specialist support, we help identify the appropriate Daron Group resources.",
  networkCta: "Explore the group connection", groupSite: "Visit Daron Group", localLabel: "YOUR LOCAL STARTING POINT", localTitle: "Walvis Bay, Namibia", localBody: "Vessel supply, technical procurement and delivery coordination. Bring your requirement to the Namibia operations team.",
  networkSteps: [
    { title: "International sourcing", body: "The group describes procurement and cargo consolidation from Europe and South Africa. Discuss how these resources may support your requirement.", href: "https://daron-group.com/supply-chain-logistics/" },
    { title: "Technical expertise", body: "Explore group capabilities in coatings, lubricants, chemicals and maintenance support. Our team can help identify the appropriate technical contact.", href: "https://daron-group.com/technical/" },
    { title: "Food & project supply", body: "D-Food describes central purchasing and food and non-food consolidation for catering and distribution. Discuss your product list and delivery location.", href: "https://daron-group.com/dfood/" },
  ],
  scopeNote: "Group capabilities are shown for context. Availability in Namibia, the delivery scope and the responsible contracting entity are confirmed for each requirement.",
  networkPageIntro: "A local point of contact, with a wider network to explore. Tell us what you need and where it needs to go; our Namibia team will discuss the available route with you.",
  locationsTitle: "Find the appropriate group office", locationsBody: "The group contact directory lists offices in France, Gabon, Congo, Angola, Namibia, Mozambique and South Africa. Use the directory for direct office details, or start your discussion with Namibia.", locationsCta: "Open the group contact directory",
  processTitle: "A clear handoff starts with a clear scope.", process: ["Send your requirement to Namibia, including locations and dates.", "Our team reviews local scope and any group support needed.", "Confirm the responsible team, quotation and delivery arrangements before work begins."],
  solutionsEyebrow: "PLAN THE WHOLE REQUIREMENT", solutionsTitle: "What are you preparing for?", solutionsIntro: "Start with your operation. Bring related supply needs into one conversation, with the scope and delivery arrangements agreed by our team.",
  solutionsCta: "Explore support for your operation", localScope: "Discuss with Namibia", groupScope: "Explore through the group", prepareTitle: "Help us understand your requirement", evidenceTitle: "Relevant experience", evidenceCta: "Explore the project", groupCapability: "Explore group capability", requestCta: "Discuss this requirement", back: "All operational solutions", related: "Other requirements", resourcesLink: "Procurement resources",
  solutions: {
    "vessel-reactivation": { ...evidence["vessel-reactivation"], title: "Vessel reactivation", intro: "Bring provisions, cleaning, safety equipment and technical supply into one reactivation discussion. Share the vessel schedule and work list so our team can review priorities and sourcing requirements.", local: ["Provisions, cabin stores and crew supplies", "Cleaning chemicals, coatings and technical procurement", "Delivery coordination against the vessel schedule"], group: ["Specialist products and sourcing through appropriate group contacts", "Supply requirements involving another group location"], prepare: ["Vessel name, location and target readiness date", "Department lists, quantities and technical specifications", "Delivery sequence and any items on the critical path"], evidence: "Read Daron Namibia’s published Sapura Berani reactivation story. The photograph here shows separate Daron quayside work; it is not a photograph of that reactivation." },
    "planned-maintenance": { ...evidence["planned-maintenance"], title: "Planned maintenance & shutdowns", intro: "Prepare the supply scope before the maintenance window opens. Discuss coatings, surface preparation, chemicals, safety products and technical consumables with our Walvis Bay team.", local: ["Coating and surface-preparation requirements", "Cleaning chemicals and safety equipment", "Technical consumables and delivery planning"], group: ["Specialist anti-corrosion, lubricant and maintenance product enquiries", "Inspection or additional technical support, subject to an agreed scope"], prepare: ["Asset, substrate, exposure conditions and existing coating", "Work scope, quantities or surface area, and required documents", "Maintenance dates, delivery location and technical approval requirements"], evidence: "Explore Daron Namibia’s dry-dock and vessel-maintenance portfolio, including the before-and-after coating imagery shown here." },
    "remote-site-supply": { ...evidence["remote-site-supply"], title: "Remote-site mobilisation & supply", intro: "Planning a new site or a recurring supply programme? Discuss provisions, hygiene products, PPE and technical stores, with delivery requirements assessed for your location.", local: ["Food, hygiene, safety and technical supply enquiries", "Product-list consolidation and procurement discussion", "Delivery planning based on site location and access"], group: ["D-Food sourcing and consolidation capabilities", "Modular accommodation or project support through the relevant group team"], prepare: ["Site location, access constraints and mobilisation date", "Headcount, supply frequency and storage arrangements", "Product list and any accommodation or project-support requirements"], evidence: "Group reference: accommodation and ablution blocks supplied and installed in Mueda, Mozambique, reported in July 2022. This is group experience, not a Namibia project. The photograph above shows Daron Namibia’s marine supply operation." },
  } satisfies Record<SolutionSlug, Solution>,
  resourcesTitle: "Make your supplier review easier.", resourcesIntro: "Find product information and service context, or ask our operations team for the documents your onboarding process requires.", resourcesEyebrow: "PROCUREMENT RESOURCES", catalogueTitle: "Product catalogues", catalogueBody: "Browse brand documents and add relevant catalogues to your enquiry. Include a page, product reference and quantity to help our team respond.", catalogueCta: "Browse brands & catalogues", capabilityTitle: "Namibia capability overview", capabilityBody: "Review our local services, technical brands and project experience. Use the group-network page to understand the wider context.", capabilityCta: "Explore Namibia services", onboardingTitle: "Supplier onboarding documents", onboardingBody: "Tell us your organisation’s registration requirements, required documents and deadline. Our team will confirm which current documents can be shared and which entity they cover.", onboardingCta: "Request onboarding documents", documentNote: "Certificates and corporate records are supplied by the team where applicable. Confirm the entity, scope and validity of each document during your review.",
};
type GrowthContent = typeof en;
const fr: GrowthContent = {
  ...en, networkEyebrow: "NAMIBIE & GROUPE DARON", networkTitle: "Un interlocuteur local. Les capacités du groupe.", networkIntro: "Commencez avec notre équipe de Walvis Bay. Pour les besoins concernant d’autres marchés ou un soutien spécialisé, nous vous aidons à identifier les ressources appropriées du groupe Daron.", networkCta: "Découvrir le lien avec le groupe", groupSite: "Visiter Daron Group", localLabel: "VOTRE POINT DE DÉPART LOCAL", localTitle: "Walvis Bay, Namibie", localBody: "Approvisionnement des navires, achats techniques et coordination des livraisons. Présentez votre besoin à l’équipe opérationnelle namibienne.",
  networkSteps: [
    { title: "Achats internationaux", body: "Le groupe présente des capacités d’achat et de consolidation de fret depuis l’Europe et l’Afrique du Sud. Discutons de leur pertinence pour votre besoin.", href: en.networkSteps[0].href },
    { title: "Expertise technique", body: "Découvrez les capacités du groupe en revêtements, lubrifiants, produits chimiques et maintenance. Notre équipe peut identifier le contact technique approprié.", href: en.networkSteps[1].href },
    { title: "Alimentation & projets", body: "D-Food présente des achats centralisés et la consolidation de produits alimentaires et non alimentaires. Partagez votre liste et le lieu de livraison.", href: en.networkSteps[2].href },
  ], scopeNote: "Les capacités du groupe sont présentées à titre de contexte. Leur disponibilité en Namibie, le périmètre de livraison et l’entité contractante sont confirmés pour chaque demande.", networkPageIntro: "Un interlocuteur local et un réseau plus large à explorer. Indiquez vos besoins et leur destination ; notre équipe namibienne étudiera les possibilités avec vous.", locationsTitle: "Trouver le bureau approprié", locationsBody: "L’annuaire du groupe répertorie des bureaux en France, au Gabon, au Congo, en Angola, en Namibie, au Mozambique et en Afrique du Sud. Consultez leurs coordonnées ou commencez avec la Namibie.", locationsCta: "Ouvrir l’annuaire du groupe", processTitle: "Une coordination claire commence par un périmètre clair.", process: ["Envoyez votre besoin à la Namibie, avec les lieux et les dates.", "Notre équipe examine le périmètre local et le soutien éventuel du groupe.", "Confirmez l’équipe responsable, le devis et les modalités de livraison avant le début des travaux."],
  solutionsEyebrow: "PLANIFIER L’ENSEMBLE DU BESOIN", solutionsTitle: "Quelle opération préparez-vous ?", solutionsIntro: "Regroupez vos besoins d’approvisionnement dans une seule discussion, avec un périmètre et des modalités convenus par notre équipe.", solutionsCta: "Explorer le soutien à votre opération", localScope: "À discuter avec la Namibie", groupScope: "À explorer avec le groupe", prepareTitle: "Aidez-nous à comprendre votre besoin", evidenceTitle: "Expérience pertinente", evidenceCta: "Découvrir le projet", groupCapability: "Explorer les capacités du groupe", requestCta: "Discuter de ce besoin", back: "Toutes les solutions opérationnelles", related: "Autres besoins", resourcesLink: "Ressources achats",
  solutions: {
    "vessel-reactivation": { ...evidence["vessel-reactivation"], title: "Remise en service d’un navire", intro: "Regroupez les provisions, le nettoyage, la sécurité et les fournitures techniques. Partagez le calendrier du navire et la liste des travaux pour examiner les priorités.", local: ["Provisions, fournitures de cabine et besoins de l’équipage", "Produits de nettoyage, revêtements et achats techniques", "Coordination des livraisons selon le calendrier du navire"], group: ["Produits spécialisés et achats via les contacts appropriés du groupe", "Besoins impliquant un autre site du groupe"], prepare: ["Nom du navire, lieu et date de remise en service visée", "Listes par service, quantités et spécifications", "Ordre des livraisons et articles critiques"], evidence: "Consultez le récit publié par Daron Namibia sur Sapura Berani. La photographie montre une autre opération à quai ; elle ne représente pas cette remise en service." },
    "planned-maintenance": { ...evidence["planned-maintenance"], title: "Maintenance planifiée & arrêts techniques", intro: "Préparez les approvisionnements avant l’ouverture de la fenêtre de maintenance. Discutez des revêtements, de la préparation des surfaces, des produits chimiques et de sécurité avec notre équipe.", local: ["Revêtements et préparation des surfaces", "Produits de nettoyage et équipements de sécurité", "Consommables techniques et planification des livraisons"], group: ["Demandes spécialisées en anticorrosion, lubrifiants et maintenance", "Inspection ou soutien technique supplémentaire selon un périmètre convenu"], prepare: ["Actif, support, exposition et revêtement existant", "Travaux, quantités ou surfaces et documents requis", "Dates, lieu de livraison et validations techniques"], evidence: "Découvrez les travaux de cale sèche et de maintenance de Daron Namibia, notamment les images avant/après de revêtement présentées ici." },
    "remote-site-supply": { ...evidence["remote-site-supply"], title: "Mobilisation & approvisionnement de sites isolés", intro: "Nouveau site ou programme régulier ? Discutez des provisions, de l’hygiène, des EPI et des fournitures techniques, avec une étude des besoins de livraison propres au site.", local: ["Demandes alimentaires, d’hygiène, de sécurité et techniques", "Consolidation des listes et discussion des achats", "Planification selon le lieu et les accès au site"], group: ["Achats et consolidation via D-Food", "Hébergement modulaire ou soutien de projet via l’équipe appropriée"], prepare: ["Lieu, contraintes d’accès et date de mobilisation", "Effectifs, fréquence et possibilités de stockage", "Liste de produits et besoins d’hébergement ou de projet"], evidence: "Référence du groupe : fourniture et installation de blocs d’hébergement et sanitaires à Mueda, au Mozambique, publiées en juillet 2022. Il ne s’agit pas d’un projet namibien. La photographie montre une opération maritime de Daron Namibia." },
  }, resourcesTitle: "Facilitez votre évaluation fournisseur.", resourcesIntro: "Consultez les informations produits et services, ou demandez les documents nécessaires à votre référencement.", resourcesEyebrow: "RESSOURCES ACHATS", catalogueTitle: "Catalogues produits", catalogueBody: "Consultez les documents et ajoutez les catalogues pertinents à votre demande. Précisez la page, la référence et la quantité.", catalogueCta: "Marques & catalogues", capabilityTitle: "Les capacités en Namibie", capabilityBody: "Consultez nos services locaux, marques techniques et expériences. Découvrez aussi le contexte du réseau du groupe.", capabilityCta: "Services en Namibie", onboardingTitle: "Documents de référencement", onboardingBody: "Indiquez les exigences de votre organisation, les documents et l’échéance. Notre équipe confirmera les documents actuels pouvant être partagés et l’entité concernée.", onboardingCta: "Demander les documents", documentNote: "L’équipe fournit les certificats et documents d’entreprise applicables. Confirmez l’entité, le périmètre et la validité lors de votre évaluation.",
};
const pt: GrowthContent = {
  ...en, networkEyebrow: "NAMÍBIA & GRUPO DARON", networkTitle: "Responsabilidade local. Capacidade do grupo.", networkIntro: "Comece com a nossa equipa de Walvis Bay. Para necessidades noutros mercados ou apoio especializado, ajudamos a identificar os recursos adequados do Grupo Daron.", networkCta: "Conhecer a ligação ao grupo", groupSite: "Visitar Daron Group", localLabel: "O SEU PONTO DE PARTIDA LOCAL", localTitle: "Walvis Bay, Namíbia", localBody: "Abastecimento de navios, compras técnicas e coordenação de entregas. Apresente a sua necessidade à equipa operacional da Namíbia.",
  networkSteps: [
    { title: "Compras internacionais", body: "O grupo apresenta capacidade de compras e consolidação de carga da Europa e África do Sul. Fale connosco sobre a sua aplicação à sua necessidade.", href: en.networkSteps[0].href },
    { title: "Conhecimento técnico", body: "Explore as capacidades do grupo em revestimentos, lubrificantes, químicos e manutenção. A nossa equipa pode identificar o contacto técnico adequado.", href: en.networkSteps[1].href },
    { title: "Alimentação & projetos", body: "A D-Food apresenta compras centralizadas e consolidação de produtos alimentares e não alimentares. Partilhe a lista e o local de entrega.", href: en.networkSteps[2].href },
  ], scopeNote: "As capacidades do grupo são apresentadas como contexto. A disponibilidade na Namíbia, o âmbito de entrega e a entidade contratante são confirmados para cada pedido.", networkPageIntro: "Um contacto local e uma rede mais ampla para explorar. Diga-nos o que precisa e o destino; a equipa da Namíbia analisará as possibilidades consigo.", locationsTitle: "Encontre o escritório adequado", locationsBody: "O diretório do grupo indica escritórios em França, Gabão, Congo, Angola, Namíbia, Moçambique e África do Sul. Consulte os contactos ou comece pela Namíbia.", locationsCta: "Abrir o diretório do grupo", processTitle: "Uma coordenação clara começa com um âmbito claro.", process: ["Envie a necessidade à Namíbia, incluindo locais e datas.", "A equipa analisa o âmbito local e o eventual apoio do grupo.", "Confirme a equipa responsável, a proposta e as condições de entrega antes de iniciar os trabalhos."],
  solutionsEyebrow: "PLANEIE A NECESSIDADE COMPLETA", solutionsTitle: "Que operação está a preparar?", solutionsIntro: "Reúna necessidades de abastecimento numa conversa, com o âmbito e as condições de entrega acordados pela nossa equipa.", solutionsCta: "Explorar apoio à sua operação", localScope: "A discutir com a Namíbia", groupScope: "A explorar através do grupo", prepareTitle: "Ajude-nos a compreender a necessidade", evidenceTitle: "Experiência relevante", evidenceCta: "Conhecer o projeto", groupCapability: "Explorar capacidades do grupo", requestCta: "Discutir esta necessidade", back: "Todas as soluções operacionais", related: "Outras necessidades", resourcesLink: "Recursos para compras",
  solutions: {
    "vessel-reactivation": { ...evidence["vessel-reactivation"], title: "Reativação de navios", intro: "Reúna provisões, limpeza, segurança e abastecimento técnico numa discussão de reativação. Partilhe o calendário e a lista de trabalhos para analisarmos prioridades.", local: ["Provisões, artigos de cabine e abastecimento da tripulação", "Químicos de limpeza, revestimentos e compras técnicas", "Coordenação de entregas conforme o calendário do navio"], group: ["Produtos especializados e compras através dos contactos adequados", "Necessidades que envolvam outra localização do grupo"], prepare: ["Nome do navio, localização e data prevista de prontidão", "Listas por departamento, quantidades e especificações", "Sequência de entrega e artigos críticos"], evidence: "Leia a história publicada pela Daron Namibia sobre o Sapura Berani. A fotografia mostra outra operação no cais e não essa reativação." },
    "planned-maintenance": { ...evidence["planned-maintenance"], title: "Manutenção planeada & paragens", intro: "Prepare o abastecimento antes da janela de manutenção. Discuta revestimentos, preparação de superfícies, químicos, segurança e consumíveis técnicos com a equipa de Walvis Bay.", local: ["Revestimentos e preparação de superfícies", "Químicos de limpeza e equipamentos de segurança", "Consumíveis técnicos e planeamento de entregas"], group: ["Pedidos especializados de anticorrosão, lubrificantes e manutenção", "Inspeção ou apoio técnico adicional sujeito a um âmbito acordado"], prepare: ["Ativo, substrato, exposição e revestimento existente", "Trabalhos, quantidades ou área e documentos necessários", "Datas, local de entrega e aprovações técnicas"], evidence: "Explore o portefólio de doca seca e manutenção da Daron Namibia, incluindo as imagens de revestimento antes/depois apresentadas aqui." },
    "remote-site-supply": { ...evidence["remote-site-supply"], title: "Mobilização & abastecimento de locais remotos", intro: "Novo local ou programa recorrente? Discuta provisões, higiene, EPI e artigos técnicos, com as necessidades de entrega avaliadas para a localização.", local: ["Pedidos de alimentação, higiene, segurança e artigos técnicos", "Consolidação de listas e discussão de compras", "Planeamento conforme a localização e os acessos"], group: ["Compras e consolidação através da D-Food", "Alojamento modular ou apoio de projeto através da equipa adequada"], prepare: ["Localização, limitações de acesso e data de mobilização", "Efetivo, frequência de abastecimento e armazenamento", "Lista de produtos e necessidades de alojamento ou projeto"], evidence: "Referência do grupo: fornecimento e instalação de alojamento e blocos sanitários em Mueda, Moçambique, publicados em julho de 2022. Não é um projeto da Namíbia. A fotografia mostra uma operação marítima da Daron Namibia." },
  }, resourcesTitle: "Facilite a avaliação do fornecedor.", resourcesIntro: "Encontre informações sobre produtos e serviços, ou solicite os documentos necessários ao seu processo de registo.", resourcesEyebrow: "RECURSOS PARA COMPRAS", catalogueTitle: "Catálogos de produtos", catalogueBody: "Consulte documentos e adicione catálogos ao pedido. Indique a página, a referência do produto e a quantidade.", catalogueCta: "Marcas & catálogos", capabilityTitle: "Capacidades na Namíbia", capabilityBody: "Consulte serviços locais, marcas técnicas e experiência em projetos. Explore a rede do grupo para um contexto mais amplo.", capabilityCta: "Serviços na Namíbia", onboardingTitle: "Documentos de registo de fornecedor", onboardingBody: "Indique os requisitos da organização, os documentos e o prazo. A equipa confirmará quais os documentos atuais que pode partilhar e a entidade abrangida.", onboardingCta: "Solicitar documentos", documentNote: "A equipa fornece os certificados e documentos empresariais aplicáveis. Confirme a entidade, o âmbito e a validade durante a avaliação.",
};
export function getGrowthContent(locale: string): GrowthContent { return locale === "fr" ? fr : locale === "pt" ? pt : en; }
