import Image from "next/image";
import type { Metadata } from "next";
import { setRequestLocale, getTranslations } from "next-intl/server";
import { PageHero } from "@/components/PageHero";
import { Container } from "@/components/Container";
import { InlineRFQ } from "@/components/InlineRFQ";
import { Link } from "@/i18n/routing";
import { buildMetadata } from "@/lib/seo";
const copy = {
  en: {title:"Coatings and surface preparation in Walvis Bay",intro:"Hempel coating supply, Hammelmann water-jetting systems and technical support for marine and industrial maintenance. Discuss the surface, environment and maintenance window with our team.",heading:"Start with the application.",body:"Share the asset, substrate, existing coating, exposure conditions and proposed work schedule. Our technical team can help identify the product information and support needed for your scope.",proof:"Vessel coating refurbishment",proofBody:"Before-and-after imagery from Daron’s vessel maintenance portfolio. Explore the project work and discuss the requirements of your own asset.",products:"Products and technical information",product1:"Hempel coatings and catalogues",product2:"Hammelmann water-jetting systems",product3:"Orlichem cleaning and surface-treatment chemicals",scope:"Send your coating requirement",scopeBody:"Attach the specification, product list or scope of work. Include surface area and delivery date if known.",description:"Explore Hempel coating supply, surface preparation and marine maintenance support in Walvis Bay. Send Daron your specification, product list or project scope."},
  fr: {title:"Revêtements et préparation de surface à Walvis Bay",intro:"Revêtements Hempel, systèmes de jet d’eau Hammelmann et soutien technique pour la maintenance marine et industrielle. Échangez avec notre équipe sur votre application.",heading:"Commençons par l’application.",body:"Précisez l’équipement, le support, le revêtement existant, l’exposition et le calendrier. Notre équipe vous aide à identifier les informations produit et le soutien adaptés.",proof:"Rénovation du revêtement d’un navire",proofBody:"Images avant et après issues de notre portfolio de maintenance navale. Découvrez nos travaux et échangez sur votre propre équipement.",products:"Produits et informations techniques",product1:"Revêtements et catalogues Hempel",product2:"Systèmes de jet d’eau Hammelmann",product3:"Nettoyage et traitement de surface Orlichem",scope:"Envoyer votre besoin en revêtements",scopeBody:"Joignez la spécification, la liste de produits ou le descriptif. Indiquez la surface et la date de livraison si connues.",description:"Revêtements Hempel, préparation de surface et soutien à la maintenance navale à Walvis Bay. Envoyez votre spécification ou descriptif de travaux à Daron."},
  pt: {title:"Revestimentos e preparação de superfície em Walvis Bay",intro:"Revestimentos Hempel, sistemas de jato de água Hammelmann e apoio técnico à manutenção naval e industrial. Fale com a nossa equipa sobre a sua aplicação.",heading:"Comecemos pela aplicação.",body:"Indique o equipamento, substrato, revestimento existente, exposição e calendário de trabalho. A equipa técnica ajuda a identificar a informação de produto e o apoio adequados.",proof:"Renovação do revestimento de um navio",proofBody:"Imagens antes e depois do nosso portfólio de manutenção naval. Conheça os trabalhos e fale connosco sobre o seu equipamento.",products:"Produtos e informação técnica",product1:"Revestimentos e catálogos Hempel",product2:"Sistemas de jato de água Hammelmann",product3:"Limpeza e tratamento de superfície Orlichem",scope:"Envie o seu pedido de revestimentos",scopeBody:"Anexe a especificação, lista de produtos ou âmbito de trabalho. Indique a área e a data de entrega, se conhecidas.",description:"Revestimentos Hempel, preparação de superfície e apoio à manutenção naval em Walvis Bay. Envie à Daron a especificação, lista de produtos ou âmbito do projeto."}
};
function content(locale:string){return copy[locale as keyof typeof copy] || copy.en;}
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const {locale}=await params;const c=content(locale);return buildMetadata({locale,path:"/services/coatings",title:c.title,description:c.description});}
export default async function CoatingsPage({params}:{params:Promise<{locale:string}>}){
  const {locale}=await params;setRequestLocale(locale);const c=content(locale);const t=await getTranslations("PremiumHome");
  return <div className="premium-home"><PageHero eyebrow={t("coatings")} title={c.title} intro={c.intro} image={{src:"/images/site/drydock/case-study-hempel-bow.jpg",alt:t("maintenanceAlt")}}><Link href="/contact#rfq" className="premium-button">{t("quote")} →</Link></PageHero>
    <section className="premium-section"><Container className="premium-team"><div><p className="premium-eyebrow">{t("brandsEyebrow")}</p><h2 className="my-5">{c.heading}</h2><p className="premium-lead">{c.body}</p><h3 className="mt-8 mb-4 text-xl font-semibold">{c.products}</h3><div className="space-y-4">{[["hempel",c.product1],["hammelmann",c.product2],["orlichem",c.product3]].map(([slug,label])=><Link className="block underline underline-offset-4" key={slug} href={`/brands/${slug}`}>{label} ↗</Link>)}</div></div><div><Image src="/images/site/drydock/case-study-hempel-bow.jpg" alt={t("maintenanceAlt")} width={1200} height={900} sizes="(max-width:850px) 100vw,50vw" style={{width:"100%",height:"auto"}}/><h3 className="mt-6 text-xl font-semibold">{c.proof}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{c.proofBody}</p><Link className="premium-text-link mt-5 inline-flex" href="/track-record">{t("projectCta")} →</Link></div></Container></section>
    <InlineRFQ heading={c.scope} body={c.scopeBody}/></div>;
}
