import fs from 'node:fs';
const copy = {
 en: { affiliation:'Part of Daron Group', solutions:'Solutions', group:'Group network', resources:'Procurement resources', loading:'Loading your enquiry…', addCatalogue:'Add to enquiry', added:'Added to enquiry', reviewList:'Review enquiry ({count})', listError:'Could not save the list. Check browser storage or the 10-catalogue limit. You can also describe your requirement below.', listTitle:'Your catalogue references ({count})', listHint:'Tell us which product or page you mean. Catalogue references do not confirm stock or pricing.', remove:'Remove', itemDetail:'Product reference / page / requirement', itemHint:'For example: page 12, product code and specification', quantity:'Quantity and units', quantityHint:'For example: 12 × 20 litre packs', browserSaved:'This list is saved on this browser until you remove it or submit successfully. No contact details are saved with it.', context:'Enquiry context:', multiTitle:'More than one delivery location?', multiLabel:'Locations and required dates', multiHint:'List each port or site, the required date and the relevant part of your requirement.', multiNote:'Our Namibia team will review coordination needs. Other offices and delivery arrangements are confirmed for your scope.', sources:{'vessel-reactivation':'Vessel reactivation','planned-maintenance':'Planned maintenance','remote-site-supply':'Remote-site supply','group-network':'Daron Group support','procurement-resources':'Supplier onboarding documents'} },
 fr: { affiliation:'Membre du groupe Daron', solutions:'Solutions', group:'Réseau du groupe', resources:'Ressources achats', loading:'Chargement de votre demande…', addCatalogue:'Ajouter à la demande', added:'Ajouté à la demande', reviewList:'Voir la demande ({count})', listError:'Impossible d’enregistrer la liste. Vérifiez le stockage du navigateur ou la limite de 10 catalogues. Vous pouvez aussi décrire votre besoin ci-dessous.', listTitle:'Vos références de catalogues ({count})', listHint:'Précisez le produit ou la page. Ces références ne confirment ni le stock ni les prix.', remove:'Retirer', itemDetail:'Référence produit / page / besoin', itemHint:'Exemple : page 12, code produit et spécification', quantity:'Quantité et unités', quantityHint:'Exemple : 12 conditionnements de 20 litres', browserSaved:'Cette liste reste dans ce navigateur jusqu’à sa suppression ou son envoi réussi. Aucune coordonnée personnelle n’y est enregistrée.', context:'Contexte de la demande :', multiTitle:'Plusieurs lieux de livraison ?', multiLabel:'Lieux et dates souhaitées', multiHint:'Indiquez chaque port ou site, la date et les besoins correspondants.', multiNote:'Notre équipe namibienne examinera la coordination. Les autres bureaux et modalités de livraison seront confirmés pour votre périmètre.', sources:{'vessel-reactivation':'Remise en service d’un navire','planned-maintenance':'Maintenance planifiée','remote-site-supply':'Approvisionnement de site isolé','group-network':'Soutien du groupe Daron','procurement-resources':'Documents de référencement fournisseur'} },
 pt: { affiliation:'Parte do Grupo Daron', solutions:'Soluções', group:'Rede do grupo', resources:'Recursos para compras', loading:'A carregar o seu pedido…', addCatalogue:'Adicionar ao pedido', added:'Adicionado ao pedido', reviewList:'Rever pedido ({count})', listError:'Não foi possível guardar a lista. Verifique o armazenamento do navegador ou o limite de 10 catálogos. Pode também descrever a necessidade abaixo.', listTitle:'As suas referências de catálogos ({count})', listHint:'Indique o produto ou a página. As referências não confirmam disponibilidade nem preços.', remove:'Remover', itemDetail:'Referência do produto / página / necessidade', itemHint:'Exemplo: página 12, código do produto e especificação', quantity:'Quantidade e unidades', quantityHint:'Exemplo: 12 embalagens de 20 litros', browserSaved:'A lista fica neste navegador até ser removida ou enviada com sucesso. Não são guardados dados de contacto com a lista.', context:'Contexto do pedido:', multiTitle:'Mais de um local de entrega?', multiLabel:'Locais e datas necessárias', multiHint:'Indique cada porto ou local, a data e a parte correspondente do pedido.', multiNote:'A equipa da Namíbia analisará a coordenação. Os outros escritórios e as condições de entrega serão confirmados para o seu âmbito.', sources:{'vessel-reactivation':'Reativação de navios','planned-maintenance':'Manutenção planeada','remote-site-supply':'Abastecimento de locais remotos','group-network':'Apoio do Grupo Daron','procurement-resources':'Documentos de registo de fornecedor'} },
};
for(const [locale,Growth] of Object.entries(copy)) {
 const path=`messages/${locale}.json`;const messages=JSON.parse(fs.readFileSync(path,'utf8'));
 messages.Growth=Growth;messages.Nav.solutions=Growth.solutions;
 fs.writeFileSync(path,JSON.stringify(messages,null,2)+'\n');
}
