import type { Metadata, Viewport } from "next";
import Script from "next/script";
import { Poppins, Open_Sans } from "next/font/google";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import "../globals.css";

import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { JsonLd } from "@/components/JsonLd";
import { ChatWidget } from "@/components/ChatWidget";
import { RevealController } from "@/components/RevealController";
import { contact, site } from "@/lib/site";
import { routing } from "@/i18n/routing";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "600"],
  display: "swap",
});

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "Meta" });

  const ogLocale =
    locale === "pt" ? "pt_PT" : locale === "fr" ? "fr_FR" : "en_NA";

  return {
    metadataBase: new URL(site.url),
    title: {
      default: t("homeTitle"),
      template: `%s | ${site.name}`,
    },
    description: t("homeDescription"),
    // Per-page canonical + hreflang are set by buildMetadata() in each page.
    // The branded social card is generated by [locale]/opengraph-image.tsx,
    // so no images array is hard-coded here (every page inherits the card).
    openGraph: {
      type: "website",
      siteName: site.name,
      title: t("homeTitle"),
      description: t("homeDescription"),
      locale: ogLocale,
      url: site.url,
    },
    twitter: {
      card: "summary_large_image",
      title: site.name,
      description: t("homeDescription"),
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
  };
}

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // NOTE: deliberately no maximumScale or userScalable — current site fails WCAG
  // by blocking pinch-zoom; we must not inherit that. (CLAUDE.md audit fix #6)
};

const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: site.name,
  url: site.url,
  description: site.description,
  inLanguage: ["en", "pt", "fr"],
  publisher: {
    "@type": "Organization",
    name: site.name,
    url: site.url,
  },
};

const orgJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: site.name,
  legalName: site.legalName,
  url: site.url,
  foundingDate: String(site.founded),
  description: site.description,
  email: contact.emails.operations,
  telephone: contact.phone.e164,
  sameAs: [contact.socials.linkedin, contact.socials.facebook],
  address: {
    "@type": "PostalAddress",
    streetAddress: `${contact.address.line1}, ${contact.address.line2}`,
    addressLocality: contact.address.city,
    addressRegion: contact.address.region,
    addressCountry: "NA",
  },
};

const localBusinessJsonLd = {
  "@context": "https://schema.org",
  "@type": "LocalBusiness",
  name: site.name,
  image: `${site.url}/images/site/operations/normand-energy-wide.jpg`,
  url: site.url,
  telephone: contact.phone.e164,
  email: contact.emails.operations,
  priceRange: "$$",
  address: {
    "@type": "PostalAddress",
    streetAddress: `${contact.address.line1}, ${contact.address.line2}`,
    addressLocality: contact.address.city,
    addressRegion: contact.address.region,
    addressCountry: "NA",
  },
  geo: {
    "@type": "GeoCoordinates",
    latitude: -22.957,
    longitude: 14.508,
  },
  openingHoursSpecification: [
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
      ],
      opens: "08:00",
      closes: "17:00",
    },
  ],
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);
  const tA11y = await getTranslations("A11y");

  return (
    <html
      lang={locale}
      suppressHydrationWarning
      className={`${poppins.variable} ${openSans.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col bg-white text-[var(--color-ink)]">
        {/* Set .js before paint so the scroll-reveal CSS only hides content
            when JS can reveal it again (no-JS / reduced-motion stay visible). */}
        <script
          dangerouslySetInnerHTML={{
            __html: "document.documentElement.classList.add('js')",
          }}
        />
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-[100] focus:rounded-md focus:bg-[var(--color-navy)] focus:px-4 focus:py-2 focus:text-sm focus:font-semibold focus:text-white"
        >
          {tA11y("skipToContent")}
        </a>
        <NextIntlClientProvider>
          <Header />
          <main id="main" tabIndex={-1} className="flex-1 outline-none">
            {children}
          </main>
          <Footer />
          <JsonLd id="ld-website" data={websiteJsonLd} />
          <JsonLd id="ld-organization" data={orgJsonLd} />
          <JsonLd id="ld-localbusiness" data={localBusinessJsonLd} />
          <ChatWidget />
          <RevealController />
        </NextIntlClientProvider>
        {/* Plausible — cookieless, privacy-friendly analytics (no consent banner
            needed). Tagged-events variant powers conversion events via CSS
            classes (plausible-event-name=…). No-op until the daron.com.na site
            is created in the Plausible account. */}
        <Script
          defer
          data-domain="daron.com.na"
          src="https://plausible.io/js/script.tagged-events.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
